### ISSUE TITLE
Create index.html directly from README.md

### ISSUE THREAD

**Issue by jhale** [FEniCS/docs#1]
It is not possible to use automated Jekyll and Sphinx's `_` prepended directories at the same time.

**Comment by chrisrichardson** [comment]
The Actions now produces a "_site" folder, which could be copied back into the repo - although this seems complex and has the danger of possible infinite recursion if not handled carefully.
Maybe we can just make index.html by hand, and upload changes (with assets) manually whenever needed.

**Comment by garth-wells** [comment]
@jhale can this be closed?

**Comment by jhale** [comment]
Yes.
